version: '3.9'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1